blueprint:
  name: Frigate LLM Notification Latest (v0.42)
  author: whag
  description: >
     ...
  domain: automation
  input:
    frigate:
      ...
    llm:
      ...
    image_analyse:
      ...
      prompt_car:
        name: Prompt для объекта "car"
        description: Промпт для анализа изображения с автомобилем.
        default: "Опишите автомобиль на изображении. Сфокусируйтесь на его типе, цвете и возможных действиях."
        selector:
          text:
            multiline: true
            multiple: false
      prompt_person:
        name: Prompt для объекта "person"
        description: Промпт для анализа изображения с человеком.
        default: "Опишите человека на изображении. Обратите внимание на его действия и возможные намерения."
        selector:
          text:
            multiline: true
            multiple: false
      prompt_cat:
        name: Prompt для объекта "cat"
        description: Промпт для анализа изображения с котом.
        default: "Опишите кота на изображении. Обратите внимание на его поведение и окружение."
        selector:
          text:
            multiline: true
            multiple: false
      prompt_dog:
        name: Prompt для объекта "dog"
        description: Промпт для анализа изображения с собакой.
        default: "Опишите собаку на изображении. Обратите внимание на ее поведение и возможные действия."
        selector:
          text:
            multiline: true
            multiple: false
      prompt_bird:
        name: Prompt для объекта "bird"
        description: Промпт для анализа изображения с птицей.
        default: "Опишите птицу на изображении. Обратите внимание на ее вид и поведение."
        selector:
          text:
            multiline: true
            multiple: false
    notify:
      ...
      in_telegram_bot:
        name: Telegram Bot
        description: Выберите Telegram-бота для отправки уведомлений.
        selector:
          config_entry:
            integration: telegram_bot
      in_telegram_chat_id:
        name: Telegram Chat ID
        description: ID чата или имя пользователя Telegram, куда будут отправляться уведомления.
        default: ""
        selector:
          text:
            multiline: false
            multiple: false
  actions:
    ...
    - alias: Event is new or update Do LLM image analysis and send notification
      if:
        - condition: trigger
          id:
            - New event
      then:
        ...
        - alias: Send notification to Telegram
          if:
            - condition: template
              value_template: "{{ in_telegram_chat_id != '' }}"
          then:
            - action: telegram_bot.send_message
              
                message: "{{msg}}"
                title: "{{title}}"
                chat_id: "{{in_telegram_chat_id}}"
                parse_mode: "HTML"
                disable_notification: false
                data:
                  photo:
                    - url: "{{host}}{{image}}"
    - alias: Event is end Do LLM video analysis and send notification
      if:
        - condition: trigger
          id:
            - End event
      then:
        ...
        - alias: Update notification in Telegram
          if:
            - condition: template
              value_template: "{{ in_telegram_chat_id != '' }}"
          then:
            - action: telegram_bot.send_message
              
                message: "{{response.response_text}}"
                title: "{{response.title if gen_title2 else title_clip}}"
                chat_id: "{{in_telegram_chat_id}}"
                parse_mode: "HTML"
                disable_notification: false
                
                  video:
                    - url: "{{host}}{{video}}"
  variables:
    ...
    prompt:
      "{{ 'prompt_' + objects[0] if objects[0] in ['car', 'person', 'cat', 'dog', 'bird'] else prompt }}"
mode: parallel
max: 4
