blueprint:
  name: Frigate LLM Notification with Telegram (v0.43)
  author: whag (modified by Grok)
  description: >
     Basic requirements:<br />
     - Home Assistant with an MQTT broker setup. <br />
     - Frigate integration with MQTT setup. <br />
     Link: https://github.com/blakeblackshear/frigate-hass-integration <br />
     - LLM Vision integration with provider setup. <br />
     Link: https://github.com/valentinfrlch/ha-llmvision <br />
     - Downloader integration. <br />
     Link: https://www.home-assistant.io/integrations/downloader/ <br />
     - Telegram Bot integration setup in Home Assistant. <br />
     Link: https://www.home-assistant.io/integrations/telegram_bot/ <br /><br />
     
     Information:<br />
     - Only suitable for one Frigate camera, use multiple instances of this automation for multiple cameras if required. <br />
     - LLM Vision requires a provider setup for the automation to function, remember and memory options are optional. <br />
     - Telegram notifications require a Telegram bot and chat ID configured in Home Assistant. <br /><br />
     Description: <br />
     Use LLM Vision to analyze Frigate snapshots and clips, sending notifications via the Home Assistant companion app and Telegram. <br />
     Monitors MQTT frigate/reviews topic of types [new],[update] and [end]. <br />
     The Downloader integration is used for storing Frigate files locally before sending to LLM. <br />
     Note that the downloader folder will need maintenance separately (e.g., old files deleted or backed up). <br />
     This automation runs in parallel mode. <br /><br />
     Tested on Android and Telegram. <br /><br />
     
     Variables which may be useful for the custom message and AI prompts
       - {{input_objects}} = Objects required<br />
       - {{objects}} = Objects found<br />
       - {{input_camera_name}} = Camera required<br />
       - {{camera_name}} = Camera triggered<br />
       - {{zone_names}} = Zones required<br />
       - {{before_zones}} = Zones triggered first<br />
       - {{after_zones}} = Zones triggered last<br />
       - {{detections[0]}} = Event ID 1 (i.e., triggering event)<br />
       - {{detections[1]}} = Event ID 2<br />

     Version: v 0.43

  domain: automation
  input:
    frigate:
      name: Frigate Options
      icon: mdi:cog
      description: Frigate options
      collapsed: true
      input:
        in_camera:
          name: Frigate Camera
          description: Frigate cameras only
          selector:
            entity:
              multiple: false
              filter:
                - integration: frigate
                  domain: camera
        in_severity:
          name: Severity
          description: Frigate event severity.
          default: 
            - alert
            - detection
          selector:
            select:
              options:
                - label: Alert
                  value: alert
                - label: Detection
                  value: detection
              multiple: true
        in_zones:
          name: Frigate Zones
          description: Zones required for the alert. Filter will show all frigate devices (zones and cameras).
          default: []
          selector:
            device:
              multiple: true
              filter:
                - integration: frigate
              entity:
                - domain: binary_sensor
        in_custom_zones:
          name: Custom zones
          description: Add any custom zones not shown in the above selector.
          default: []
          selector:
            text:
              multiline: false
              multiple: true
        in_all_zones:
          name: All Zones
          description: All zones have to be entered before processing rather than any.
          default: false
          selector:
            boolean: {}
        in_objects:
          name: Required Objects
          description: Frigate objects required in the selected zones if any.
          default: []
          selector:
            select:
              multiple: true
              custom_value: true
              options:
                - person
                - bicycle
                - car
                - motorcycle
                - airplane
                - bus
                - train
                - boat
                - traffic light
                - fire hydrant
                - street sign
                - stop sign
                - parking meter
                - bench
                - bird
                - cat
                - dog
                - horse
                - sheep
                - cow
                - elephant
                - bear
                - zebra
                - giraffe
                - hat
                - backpack
                - umbrella
                - shoe
                - eye glasses
                - handbag
                - tie
                - suitcase
                - frisbee
                - skis
                - snowboard
                - sports ball
                - kite
                - baseball bat
                - baseball glove
                - skateboard
                - surfboard
                - tennis racket
                - bottle
                - plate
                - wine glass
                - cup
                - fork
                - knife
                - spoon
                - bowl
                - banana
                - apple
                - sandwich
                - orange
                - broccoli
        in_sub_labels:
          name: Sub Labels Required
          description: Frigate sub labels required in the selected zones if any.
          default: []
          selector:
            text:
              multiline: false
              multiple: true
        in_host:
          name: Home Assistant IP Address
          description: Home Assistant IP address.
          default: http://192.168.1.1:8123
          selector:
            text:
              multiline: false
              multiple: false
    llm:
      name: LLM Vision Provider / Model
      icon: mdi:cog
      description: LLM Vision options
      collapsed: true
      input:
        provider:
          name: Provider
          description: Provider to use for analysis.
          selector:
            config_entry:
              integration: llmvision
        model:
          name: AI Model
          description: AI Model
          default: gemini-1.5-flash
          selector:
            select:
              options: 
                - gpt-4o
                - gpt-4o-mini
                - gpt-4.1
                - claude-3-7-sonnet-latest
                - claude-3-5-sonnet-latest
                - claude-3-5-haiku-latest
                - claude-sonnet-4-20250514
                - claude-opus-4-20250514
                - gemini-1.5-flash
                - gemini-1.5-pro
                - gemini-2.0-flash
                - gemini-2.0-flash-lite
                - gemini-2.5-pro
                - gemini-2.5-flash
                - llama-3.2-90b-vision-preview
                - llama-3.2-11b-vision-preview
                - Llama-4-Scout-17B-16E-Instruct-FP8
                - Llama-4-Maverick-17B-16E-Instruct-FP8
              multiple: false
              custom_value: true
    image_analyse:
      name: Snapshot Analyse
      icon: mdi:cog
      description: Frigate event snapshot analyse options
      collapsed: true
      input:
        in_title_image:
          name: No AI Notification Title
          description: Notification title for snapshot. If using LLM for image analysis and want an AI-generated title, ensure [Generate Title] below is enabled.
          default: "{{camera_name}} - {{sub_labels| join(',')|replace('_', ' ')}} Alert"
          selector:
            text:
        in_custom_msg:
          name: No AI Notification Message
          description: Initial notification message if not using LLM Vision for the snapshot analysis.
          default: "A {{objects| join(' and a ')|replace('_', ' ')}} was detected in the {{after_zones| join(' and the ')|replace('_', ' ')}}" 
          selector:
            text:
              multiline: true
              multiple: false
        in_use_llm_image:
          name: LLM Vision Snapshot
          description: Use LLM Vision for initial snapshot analysis. If off, the custom message above will be used to generate the notification.
          default: true
          selector:
            boolean: {}
        prompt:
          name: Prompt 
          description: Model prompt.
          default: >
            Summarise the image in a 1 sentence response,
            concentrate on the {{input_objects| join(',')|replace('_', ' ')}} if seen within
            the {{zone_names| join(' and ,')|replace('_',' ')}}. 
            Any person approaching the camera should take priority over all other events.
            If you see a known person from memory, mention this in the response.
            Do not mention the prompt or describe the environment in your response.
            The response is an initial alert for a mobile phone security notification. 
          selector:
            text:
              multiline: true
              multiple: false
        target_width: 
          name: Pixels  
          description: Width in pixels to downscale.
          default: 1080
          selector:
            number:
              min: 512
              max: 1920
              step: 10
              mode: slider
        tokens: 
          name: Tokens 
          description: Maximum number of tokens to generate.
          default: 100
          selector:
            number:
              min: 1
              max: 300
              step: 1
              mode: slider
        in_gen_title:
          name: Generate Title
          description: AI-generated notification title.
          default: false
          selector:
            boolean: {}
        use_memory:
          name: Use Memory 
          description: Use information stored in memory to provide additional context. Memory must be set up in LLM Vision.
          default: false
          selector:
            boolean: {}
        use_remember:
          name: Use Remember 
          description: Store this event in the timeline. Timeline must be set up in LLM Vision.
          default: false
          selector:
            boolean: {}
        expose_image:
          name: Expose Image
          description: Save image in llmvision for Timeline. Timeline must be set up in LLM Vision.
          default: false
          selector:
            boolean: {}
        delay_image:
          name: Delay Before Image
          description: Delay in seconds before processing Frigate snapshot.
          default: 2
          selector: 
            number:
              min: 0
              max: 60
              step: 1
              mode: slider
    clip_analyse:
      name: Review Clip Analyse
      icon: mdi:cog
      collapsed: true
      description: Frigate review clip analyse options
      input:
        in_title_clip:
          name: No AI Notification Title
          description: Notification title for review clip. If you want an AI-generated title, ensure [Generate Title] below is enabled.
          default: "{{camera_name}} - {{sub_labels| join(',')|replace('_', ' ')}} Alert Update"
          selector:
            text:
              multiline: false
              multiple: false
        prompt2:
          name: Prompt 
          description: Model prompt.
          default: >
            Analyse the video clip which should contain the following objects {{input_objects| join(',')|replace('_', ' ')}}.
            The areas of interest are the {{zone_names| join(' and ,')|replace('_',' ')}}.
            Focus on the objects referenced previously which are entering the areas of interest and describe what they are doing.
            Consider what the {{input_objects|join(',')|replace('_',' ')}} is doing, why, and what it might do next.
            Do not mention the prompt or describe the environment in your response.  
            Your response will be used for a mobile phone notification message with the clip attached.
          selector:
            text:
              multiline: true
              multiple: false
        target_width2: 
          name: Pixels 
          description: Width in pixels to downscale.
          default: 1080
          selector:
            number:
              min: 512
              max: 1920
              step: 10
              mode: slider
        tokens2: 
          name: Tokens 
          description: Maximum number of tokens to generate.
          default: 100
          selector:
            number:
              min: 1
              max: 300
              step: 1
              mode: slider
        max_frames:
          name: Max Frames
          description: How many frames to analyze for clip.
          default: 3
          selector:
            number:
              min: 1
              max: 10
              step: 1
              mode: slider
        in_gen_title2:
          name: Generate Title
          description: AI-generated clip title.
          default: false
          selector:
            boolean: {}
        use_memory2:
          name: Use Memory
          description: Use information stored in memory to provide additional context. Memory must be set up in LLM Vision.
          default: false
          selector:
            boolean: {}
        use_remember2:
          name: Use Remember
          description: Store this event in the timeline. Timeline must be set up in LLM Vision.
          default: false
          selector:
            boolean: {}
        expose_clip:
          name: Expose Clip
          description: Save clip in llmvision for Timeline. Timeline must be set up in LLM Vision.
          default: false
          selector:
            boolean: {}
        delay_clip:
          name: Delay Before Clip
          description: Time in seconds before processing the Frigate clip.
          default: 2
          selector:
            number:
              min: 0
              max: 60
              step: 1
              mode: slider
    Downloader:
      name: Downloader Options
      icon: mdi:cog
      collapsed: true
      input:
        in_downloader:
          name: Downloader Directory 
          description: Downloader integration root directory.
          default: downloader
          selector:
            text:
              multiline: false
              multiple: false
        in_downloader_sub:
          name: Downloader Sub Directory
          description: Define a sub directory within your downloader root directory.
          default: 
          selector:
            text:
              multiline: false
              multiple: false
        download_image_wait:
          name: Image Download Max Wait Time
          description: Maximum time to wait in seconds for the Frigate image to be downloaded before retrying download.
          default: 5
          selector:
            number:
              min: 1
              max: 120
              step: 1
              mode: slider
        download_clip_wait:
          name: Clip Download Max Wait Time
          description: Maximum time to wait in seconds for the Frigate clip to be downloaded before retrying download.
          default: 30
          selector:
            number:
              min: 1
              max: 120
              step: 1
              mode: slider
    telegram:
      name: Telegram Notification Options
      icon: mdi:telegram
      collapsed: true
      input:
        telegram_chat_id:
          name: Telegram Chat ID
          description: The Telegram chat ID to send notifications to (e.g., @YourChannel or user ID).
          default: ""
          selector:
            text:
              multiline: false
              multiple: false
        telegram_parse_mode:
          name: Telegram Parse Mode
          description: Message formatting (MarkdownV2 or HTML). Leave empty for plain text.
          default: ""
          selector:
            select:
              options:
                - label: None
                  value: ""
                - label: MarkdownV2
                  value: MarkdownV2
                - label: HTML
                  value: HTML
              mode: dropdown
        telegram_silent:
          name
